package formsjava_mysql;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author boris
 */
public class Cargo extends javax.swing.JFrame {
    
    private final String dbName    = Conexion_MYSQL.getDbName();
    private final String userName  = Conexion_MYSQL.getUserName();
    private final String password  = Conexion_MYSQL.getPassword();
    private final String url       = Conexion_MYSQL.getUrl();
    private final String driver    = Conexion_MYSQL.getDriver();
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q, i, id, deleteItem;
    public Cargo() {
        initComponents();
        upDateDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //=================================function============================================
    
    public void upDateDB(){
        try{
            Class.forName(driver).newInstance();
            sqlConn = DriverManager.getConnection(url + dbName, userName,password);
            pst = sqlConn.prepareStatement("SELECT * FROM C1M_ROL");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
            RecordTable.setRowCount(0);
            while(rs.next()){
                Vector columnData = new Vector();
                for(i = 1; i <= q;i++){
                    columnData.add(rs.getString("RolCod"));
                    columnData.add(rs.getString("RolRol"));
                    columnData.add(rs.getString("RolNom"));
                    columnData.add(rs.getString("RolUsu"));
                    columnData.add(rs.getString("RolEstReg"));
    
                }
                RecordTable.addRow(columnData);
            }
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    
    //=================================function============================================
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rolCod = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        usuEst = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rolRol = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rolUsu = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rolNom = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnReactivar = new javax.swing.JButton();
        btnInactivar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Codigo:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        jPanel2.add(rolCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 60, -1));

        jLabel5.setText("Estado de Registro");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        usuEst.setText("A");
        usuEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuEstActionPerformed(evt);
            }
        });
        jPanel2.add(usuEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 20, -1));

        jLabel8.setText("Rol");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        rolRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolRolActionPerformed(evt);
            }
        });
        jPanel2.add(rolRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 90, -1));

        jLabel9.setText("Usuario");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        rolUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolUsuActionPerformed(evt);
            }
        });
        jPanel2.add(rolUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 90, -1));

        jLabel10.setText("Nombre");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        rolNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolNomActionPerformed(evt);
            }
        });
        jPanel2.add(rolNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 90, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 870, 140));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(200, 255, 255));

        jTable1.setBackground(new java.awt.Color(255, 250, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Rol", "Nombre", "Usuario", "Estado de Registroo"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 690, 110));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 870, 140));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel4.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 100, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel4.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel4.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 110, -1));

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        jPanel4.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel4.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel4.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        btnReactivar.setText("Reactivar");
        btnReactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReactivarActionPerformed(evt);
            }
        });
        jPanel4.add(btnReactivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 110, -1));

        btnInactivar.setText("Inactivar");
        btnInactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInactivarActionPerformed(evt);
            }
        });
        jPanel4.add(btnInactivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 110, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 870, 150));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Rol");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(110, 110, 110))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 40));

        jLabel2.setText("Registro de rol");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 200, -1));

        jLabel6.setText("Tabla tipo de roles");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 930, 960));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private int[] flags = new int[5];
    private JFrame frame;
    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        rolCod.setText("");
        rolRol.setText("");
        rolNom.setText("");
        rolUsu.setText("");
        usuEst.setText("A");
        flags[0] = 1;
        usuEst.setEditable(false);
        rolCod.setEditable(true);
        rolRol.setEditable(true);
        rolNom.setEditable(true);
        rolUsu.setEditable(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confima si quieras salir", "MySQL Connector",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
        
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        rolCod.setText("");
        rolRol.setText("");
        rolNom.setText("");
        rolUsu.setText("");
        usuEst.setText("");
        flagsZero();
        usuEst.setEditable(false);
    }//GEN-LAST:event_btnCancelarActionPerformed
    private void flagsZero(){
        for(int i = 0;i < flags.length; i++)
            flags[i] = 0;
    }
    
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if(flags[0]==1)insert();
        else if(flags[1]==1)update();
        else if(flags[2]==1)delete();
        else if(flags[3]==1)inactive();
        else if(flags[4]==1)reactive();
        else
            JOptionPane.showMessageDialog(this, "Ninguna Accion por hacer");
        flagsZero();  
    }//GEN-LAST:event_btnActualizarActionPerformed
    private void insert(){
        try{
            Class.forName(driver).newInstance();
            sqlConn = DriverManager.getConnection(url + dbName, userName,password);

            pst = sqlConn.prepareStatement("INSERT INTO C1M_ROL (RolCod, RolRol, RolNom, RolUsu,RolEstReg)"
                    + "VALUES (?,?,?,?,?) ");
            pst.setString(1, rolCod.getText());
            pst.setString(2, rolRol.getText());
            pst.setString(3, rolNom.getText());
            pst.setString(4, rolUsu.getText());
            pst.setString(5, usuEst.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added");            
            upDateDB();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

    }
    private void update(){
        try{
            Class.forName(driver).newInstance();
            sqlConn = DriverManager.getConnection(url + dbName, userName,password);
            
            pst = sqlConn.prepareStatement("UPDATE C1M_ROL SET RolRol = ?, RolNom = ? WHERE RolCod= ? ");
            pst.setString(1, rolRol.getText());
            pst.setString(2, rolNom.getText());
            pst.setString(3, rolCod.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Uptaded");            
            upDateDB();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

    }
    private void delete(){
        try{
            Class.forName(driver).newInstance();
            sqlConn = DriverManager.getConnection(url + dbName, userName,password);
            
            pst = sqlConn.prepareStatement("UPDATE C1M_ROL SET RolEstReg = ? WHERE  RolCod = ? ");
            pst.setString(1, "*");
            pst.setString(2, rolCod.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Deleted");            
            upDateDB();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void inactive(){
        try{
            Class.forName(driver).newInstance();
            sqlConn = DriverManager.getConnection(url + dbName, userName,password);
            
            pst = sqlConn.prepareStatement("UPDATE C1M_ROL SET RolEstReg = ? WHERE RolCod = ?");
            pst.setString(1, "I");
            pst.setString(2, rolCod.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Inactive");            
            upDateDB();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
      private void reactive(){
        try{
            Class.forName(driver).newInstance();
            sqlConn = DriverManager.getConnection(url + dbName, userName,password);
            pst = sqlConn.prepareStatement("UPDATE C1M_ROL SET RolEstReg = ? WHERE RolCod = ?");
            pst.setString(1, "A");
            pst.setString(2, rolCod.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Reactive");            
            upDateDB();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        rolCod.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
        rolRol.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        rolNom.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        rolUsu.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        usuEst.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
        rolCod.setEditable(false);
        rolRol.setEditable(false);
        rolNom.setEditable(false);
        rolUsu.setEditable(false);
        usuEst.setEditable(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void usuEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuEstActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        flags[1] = 1;
        rolRol.setEditable(true);
        rolNom.setEditable(true);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        flags[2] = 1;
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnInactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactivarActionPerformed
        flags[3] = 1;
    }//GEN-LAST:event_btnInactivarActionPerformed

    private void btnReactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReactivarActionPerformed
        flags[4] = 1;
    }//GEN-LAST:event_btnReactivarActionPerformed

    private void rolRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolRolActionPerformed

    private void rolUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolUsuActionPerformed

    private void rolNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolNomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cargo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInactivar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnReactivar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField rolCod;
    private javax.swing.JTextField rolNom;
    private javax.swing.JTextField rolRol;
    private javax.swing.JTextField rolUsu;
    private javax.swing.JTextField usuEst;
    // End of variables declaration//GEN-END:variables
}
