/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formsjava_mysql;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author boris
 */
public class Persona extends javax.swing.JFrame {

    private final String dbName    = Conexion_MYSQL.getDbName();
    private final String userName  = Conexion_MYSQL.getUserName();
    private final String password  = Conexion_MYSQL.getPassword();
    private final String url       = Conexion_MYSQL.getUrl();
    private final String driver    = Conexion_MYSQL.getDriver();
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q, i, id, deleteItem;
    public Persona() {
        initComponents();
        upDateDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //=================================function============================================
    
    public void upDateDB(){
        try{
            Class.forName(driver).newInstance();
            sqlConn = DriverManager.getConnection(url + dbName, userName,password);
            pst = sqlConn.prepareStatement("SELECT * FROM C2M_PERSONA");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
            RecordTable.setRowCount(0);
            while(rs.next()){
                Vector columnData = new Vector();
                for(i = 1; i <= q;i++){
                    columnData.add(rs.getString("PerCod"));
                    columnData.add(rs.getString("PerIden"));
                    columnData.add(rs.getString("PerApePat"));
                    columnData.add(rs.getString("PerApeMat"));
                    columnData.add(rs.getString("PerNom"));
                    columnData.add(rs.getString("PerDia"));
                    columnData.add(rs.getString("PerMes"));
                    columnData.add(rs.getString("PerAño"));
                    columnData.add(rs.getString("PerCor"));
                    columnData.add(rs.getString("PerFot"));
                    columnData.add(rs.getString("PerCoo"));
                    columnData.add(rs.getString("PerCar"));
                    columnData.add(rs.getString("PerEstReg"));

                }
                RecordTable.addRow(columnData);
            }
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    
    //=================================function============================================
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        perCod = new javax.swing.JTextField();
        perIden = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        perEstReg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        perNom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        perAño = new javax.swing.JTextField();
        perApeMat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        perApePat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        perCor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        perDia = new javax.swing.JTextField();
        perMes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        perFot = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        perCoo = new javax.swing.JTextField();
        perCar = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnReactivar = new javax.swing.JButton();
        btnInactivar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Codigo:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel4.setText("Identificador:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        perCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perCodActionPerformed(evt);
            }
        });
        jPanel2.add(perCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 60, -1));
        jPanel2.add(perIden, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 100, -1));

        jLabel5.setText("Estado de Registro");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        perEstReg.setText("A");
        perEstReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perEstRegActionPerformed(evt);
            }
        });
        jPanel2.add(perEstReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 20, -1));

        jLabel7.setText("Nombre");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        perNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perNomActionPerformed(evt);
            }
        });
        jPanel2.add(perNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 110, -1));

        jLabel8.setText("año");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, -1, -1));

        perAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perAñoActionPerformed(evt);
            }
        });
        jPanel2.add(perAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 50, -1));

        perApeMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perApeMatActionPerformed(evt);
            }
        });
        jPanel2.add(perApeMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 110, -1));

        jLabel10.setText("Apellido Paterno");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        perApePat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perApePatActionPerformed(evt);
            }
        });
        jPanel2.add(perApePat, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 110, -1));

        jLabel11.setText("Apellido Materno");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        perCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perCorActionPerformed(evt);
            }
        });
        jPanel2.add(perCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 130, -1));

        jLabel12.setText("dia");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        jLabel13.setText("mes");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        perDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perDiaActionPerformed(evt);
            }
        });
        jPanel2.add(perDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 30, -1));

        perMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perMesActionPerformed(evt);
            }
        });
        jPanel2.add(perMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 30, -1));

        jLabel9.setText("Fecha Nac.");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jLabel14.setText("Cargo");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, -1, -1));

        jLabel15.setText("Correo");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        perFot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perFotActionPerformed(evt);
            }
        });
        jPanel2.add(perFot, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 130, -1));

        jLabel16.setText("foto");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));

        jLabel17.setText("Cooperativa");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, -1, -1));

        perCoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perCooActionPerformed(evt);
            }
        });
        jPanel2.add(perCoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 90, -1));

        perCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perCarActionPerformed(evt);
            }
        });
        jPanel2.add(perCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 130, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 870, 140));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(200, 255, 255));

        jTable1.setBackground(new java.awt.Color(255, 250, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Identificador", "Apellido Paterno", "Apellido Materno", "Nombre", "Nac. dia", "Nac. mes", "Nac. año", "Correo", "foto", "Cooperativa", "Cargo", "Est Registro"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 780, 110));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 870, 140));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel4.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 100, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel4.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel4.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 110, -1));

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        jPanel4.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel4.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel4.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        btnReactivar.setText("Reactivar");
        btnReactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReactivarActionPerformed(evt);
            }
        });
        jPanel4.add(btnReactivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 110, -1));

        btnInactivar.setText("Inactivar");
        btnInactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInactivarActionPerformed(evt);
            }
        });
        jPanel4.add(btnInactivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 110, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 870, 150));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Persona");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(110, 110, 110))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 40));

        jLabel2.setText("Registro de Persona");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 200, -1));

        jLabel6.setText("Tabla tipo de Persona");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 930, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private int[] flags = new int[5];
    private JFrame frame;
    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        perCod.setText("");
        perIden.setText("");
        perApePat.setText("");
        perApeMat.setText("");
        perNom.setText("");
        perDia.setText("");
        perMes.setText("");
        perAño.setText("");
        perCor.setText("");
        perFot.setText("");
        perCoo.setText("");
        perCar.setText("");
        perEstReg.setText("A");
           
        flags[0] = 1;
        
        perEstReg.setEditable(false);
        
        perCod.setEditable(true);
        perIden.setEditable(true);
        perApePat.setEditable(true);
        perApeMat.setEditable(true);
        perNom.setEditable(true);
        perDia.setEditable(true);
        perMes.setEditable(true);   
        perAño.setEditable(true);
        perCor.setEditable(true);
        perFot.setEditable(true);
        perCoo.setEditable(true);
        perCar.setEditable(true);
      
        
        
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confima si quieras salir", "MySQL Connector",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
        
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        perCod.setText("");
        perIden.setText("");
        perApePat.setText("");
        perApeMat.setText("");
        perNom.setText("");
        perDia.setText("");
        perMes.setText("");
        perAño.setText("");
        perCor.setText("");
        perFot.setText("");
        perCoo.setText("");
        perCar.setText("");
        perEstReg.setText("");
        
        
        flagsZero();
        perEstReg.setEditable(false);
    }//GEN-LAST:event_btnCancelarActionPerformed
    private void flagsZero(){
        for(int i = 0;i < flags.length; i++)
            flags[i] = 0;
    }
    
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if(flags[0]==1)insert();
        else if(flags[1]==1)update();
        else if(flags[2]==1)delete();
        else if(flags[3]==1)inactive();
        else if(flags[4]==1)reactive();
        else
            JOptionPane.showMessageDialog(this, "Ninguna Accion por hacer");
        flagsZero();  
    }//GEN-LAST:event_btnActualizarActionPerformed
    private void insert(){
        try{
            Class.forName(driver).newInstance();
            sqlConn = DriverManager.getConnection(url + dbName, userName,password);

            pst = sqlConn.prepareStatement("INSERT INTO C2M_PERSONA (PerCod, PerIden, PerApePat, PerApeMat, PerNom, PerDia, PerMes, PerAño, PerCor, PerFot, PerCoo, PerCar, PerEstReg)"
                    + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ");
            pst.setString(1, perCod.getText());
            pst.setString(2, perIden.getText());
            pst.setString(3, perApePat.getText());
            pst.setString(4, perApeMat.getText());
            pst.setString(5, perNom.getText());
            pst.setString(6, perDia.getText());
            pst.setString(7, perMes.getText());
            pst.setString(8, perAño.getText());
            pst.setString(9, perCor.getText());
            pst.setString(10, perFot.getText());
            pst.setString(11, perCoo.getText());
            pst.setString(12, perCar.getText());
            pst.setString(13, perEstReg.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added");            
            upDateDB();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

    }
    private void update(){
        try{
            Class.forName(driver).newInstance();
            sqlConn = DriverManager.getConnection(url + dbName, userName,password);
            
            pst = sqlConn.prepareStatement("UPDATE C2M_PERSONA SET PerApePat = ?, PerApeMat = ?, PerNom = ?, PerDia = ?, PerMes = ?, PerAño = ?, PerCor = ?, PerFot = ? WHERE PerCod= ? ");
            //PerApePat	PerApeMat	PerNom	PerDia	PerMes	PerAño	PerCor	PerFot	
            
            
            
            pst.setString(1, perApePat.getText());
            pst.setString(2, perApeMat.getText());
            pst.setString(3, perNom.getText());
            pst.setString(4, perDia.getText());
            pst.setString(5, perMes.getText());
            pst.setString(6, perAño.getText());
            pst.setString(7, perCor.getText());
            pst.setString(8, perFot.getText());
       
            pst.setString(9, perCod.getText());
            
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Uptaded");            
            upDateDB();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

    }
    private void delete(){
        try{
            Class.forName(driver).newInstance();
            sqlConn = DriverManager.getConnection(url + dbName, userName,password);
            //PerCod-PerIden-PerApePat-PerApeMat-PerNom-PerDia-PerMes-PerAño-PerCor-PerFot-PerCoo-PerCar-PerEstReg


            pst = sqlConn.prepareStatement("UPDATE C2M_PERSONA SET PerEstReg = ? WHERE  PerCod = ? ");
            pst.setString(1, "*");
            pst.setString(2, perCod.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Deleted");            
            upDateDB();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void inactive(){
        try{
            Class.forName(driver).newInstance();
            sqlConn = DriverManager.getConnection(url + dbName, userName,password);
            //PerCod-PerIden-PerApePat-PerApeMat-PerNom-PerDia-PerMes-PerAño-PerCor-PerFot-PerCoo-PerCar-PerEstReg

            pst = sqlConn.prepareStatement("UPDATE C2M_PERSONA SET PerEstReg = ? WHERE PerCod = ?");
            pst.setString(1, "I");
            pst.setString(2, perCod.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Inactive");            
            upDateDB();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
      private void reactive(){
        try{
            Class.forName(driver).newInstance();
            sqlConn = DriverManager.getConnection(url + dbName, userName,password);
            pst = sqlConn.prepareStatement("UPDATE C2M_PERSONA SET PerEstReg = ? WHERE PerCod = ?");
            pst.setString(1, "A");
            pst.setString(2, perCod.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Reactive");            
            upDateDB();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        //PerCod-PerIden-PerApePat-PerApeMat-PerNom-PerDia-PerMes-PerAño-PerCor-PerFot-PerCoo-PerCar-PerEstReg

        perCod.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
        perIden.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        perApePat.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        perApeMat.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        perNom.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
        perDia.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
        perMes.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
        perAño.setText(RecordTable.getValueAt(SelectedRows, 7).toString());
        perCor.setText(RecordTable.getValueAt(SelectedRows, 8).toString());
        perFot.setText(RecordTable.getValueAt(SelectedRows, 9).toString());
        perCoo.setText(RecordTable.getValueAt(SelectedRows, 10).toString());
        perCar.setText(RecordTable.getValueAt(SelectedRows, 11).toString());
        perEstReg.setText(RecordTable.getValueAt(SelectedRows, 12).toString());
        
        perCod.setEditable(false);
        perIden.setEditable(false);
        perApePat.setEditable(false);
        perApeMat.setEditable(false);
        perNom.setEditable(false);
        perDia.setEditable(false);
        perMes.setEditable(false);
        perAño.setEditable(false);
        perCor.setEditable(false);
        perFot.setEditable(false);
        perCoo.setEditable(false);
        perCar.setEditable(false);
        perEstReg.setEditable(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void perEstRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perEstRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perEstRegActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        flags[1] = 1;
        
        /*
        t = sqlConn.prepareStatement("UPDATE C2M_PERSONA SET PerApePat = ?, PerApeMat = ?, PerNom = ?, PerDia = ?, PerMes = ?, PerAño = ?, PerCor = ?, PerFot = ? WHERE PerCod= ? ");
            //PerApePat	PerApeMat	PerNom	PerDia	PerMes	PerAño	PerCor	PerFot	
            pst.setString(1, perApePat.getText());
            pst.setString(2, perApeMat.getText());
            pst.setString(3, perNom.getText());
            pst.setString(4, perDia.getText());
            pst.setString(5, perMes.getText());
            pst.setString(6, perAño.getText());
            pst.setString(7, perCor.getText());
            pst.setString(8, perFot.getText());
       
            pst.setString(9, perCod.getText());
        */
        perApePat.setEditable(true);
        perApeMat.setEditable(true);
        perNom.setEditable(true);
        
        perDia.setEditable(false);
        perMes.setEditable(false);
        perAño.setEditable(false);
        
        perCor.setEditable(true);
        perFot.setEditable(true);
        
        perCar.setEditable(false);
        perCoo.setEditable(false);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        flags[2] = 1;
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnInactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactivarActionPerformed
        flags[3] = 1;
    }//GEN-LAST:event_btnInactivarActionPerformed

    private void btnReactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReactivarActionPerformed
        flags[4] = 1;
    }//GEN-LAST:event_btnReactivarActionPerformed

    private void perNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perNomActionPerformed

    private void perAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perAñoActionPerformed

    private void perApeMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perApeMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perApeMatActionPerformed

    private void perApePatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perApePatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perApePatActionPerformed

    private void perCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perCodActionPerformed

    private void perCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perCorActionPerformed

    private void perDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perDiaActionPerformed

    private void perMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perMesActionPerformed

    private void perFotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perFotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perFotActionPerformed

    private void perCooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perCooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perCooActionPerformed

    private void perCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perCarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Persona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInactivar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnReactivar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField perApeMat;
    private javax.swing.JTextField perApePat;
    private javax.swing.JTextField perAño;
    private javax.swing.JTextField perCar;
    private javax.swing.JTextField perCod;
    private javax.swing.JTextField perCoo;
    private javax.swing.JTextField perCor;
    private javax.swing.JTextField perDia;
    private javax.swing.JTextField perEstReg;
    private javax.swing.JTextField perFot;
    private javax.swing.JTextField perIden;
    private javax.swing.JTextField perMes;
    private javax.swing.JTextField perNom;
    // End of variables declaration//GEN-END:variables
}
